apiVersion: v1
kind: ConfigMap
metadata:
  name: script-configmap
data:
  startup.sh: |
    #!/bin/bash
    set -xe 

    mkdir -p ~/.config/code-server
    cp /mnt/scripts/settings.json ~/.config/code-server

    cd ~
    git clone ${GIT_REPO_URL} 
    cd "$(ls -td -- */ | head -n 1)"
    if [ -f "init.sh" ]; then
        chmod +x ./init.sh
        ./init.sh
    fi

    /usr/bin/entrypoint.sh --bind-addr 0.0.0.0:8080 .
    
  settings.json: |
    {
      "workbench.colorTheme": "Dark+ (default dark)"
    }
  config.yaml: |
    bind-addr: 127.0.0.1:8080
    auth: password
    password: d7dadf7c3a8748f13457ad4d
    cert: false
    workbench.colorTheme: "Dark+ (default dark)"