name: Build and Deploy with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with Bun
        run: |
          git clone https://github.com/horizon-ui/shadcn-nextjs-boilerplate -o test-build-project
          cd test-build-project
          cp ../test/Dockerfile-bun .
          docker build -t my-frontend-app:latest . --file ./Dockerfile-bun

      - name: Build Docker image with Pnpm
        run: |
          git clone https://github.com/horizon-ui/shadcn-nextjs-boilerplate -o test-build-project
          cd test-build-project
          cp ../test/Dockerfile-pnpm .
          docker build -t my-frontend-app:latest . --file ./Dockerfile-pnpm
